/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RegistryWatcher {
  /**
   * 监听 HKCU 下指定子键变化；`sub_key` 用反斜杠分隔，如
   * `Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced`
   */
  constructor(subKey: string, callback: () => void)
  stop(): void
}

export declare class TaskbarCreatedWatcher {
  constructor(callback: () => void)
  stop(): void
}
export type NapiTaskbarCreatedWatcher = TaskbarCreatedWatcher

export declare class TaskbarService {
  constructor(callback: (layout: JsTaskbarLayout) => void)
  /** 嵌入窗口到任务栏。传入 Electron BrowserWindow 的 native handle (Buffer → usize) */
  embedWindowByPtr(hwndPtr: number): void
  /** 更新歌词显示宽度，触发重新计算布局 */
  update(lyricWidth: number): void
  /** 通知服务重建策略（explorer.exe 重启时由 JS 层调用） */
  reinit(): void
  /** 停止服务并恢复任务栏原始状态 */
  stop(): void
}

export declare class TrayWatcher {
  constructor(callback: () => void)
  stop(): void
}
export type NapiTrayWatcher = TrayWatcher

export declare class UiaWatcher {
  constructor(callback: () => void)
  stop(): void
}
export type NapiUiaWatcher = UiaWatcher

export interface JsAvailableSpace {
  left: JsRect
  right: JsRect
}

export interface JsExtraLayoutInfo {
  /** "win10" | "win11" */
  systemType: string
  isCentered: boolean
  /** 任务栏是否为浅色主题 */
  isLight: boolean
}

export interface JsRect {
  x: number
  y: number
  width: number
  height: number
}

export interface JsTaskbarLayout {
  space: JsAvailableSpace
  extra: JsExtraLayoutInfo
}
